# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, upload_to='course_pics'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='file_ta',
            field=models.FileField(upload_to='answer_files'),
        ),
        migrations.AlterField(
            model_name='content',
            name='file_ta',
            field=models.FileField(upload_to='content_files'),
        ),
    ]
