# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertaapp', '0002_auto_20180203_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, upload_to='ertaapp/course_pics'),
        ),
    ]
