# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertaapp', '0003_auto_20180203_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, upload_to='course_pics'),
        ),
    ]
