# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ertaapp', '0005_auto_20180203_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='file_ta',
            new_name='file_tamrin',
        ),
    ]
