# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertaapp', '0007_auto_20180203_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.IntegerField(default=2),
        ),
    ]
