# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertaapp', '0009_auto_20180204_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.IntegerField(),
        ),
    ]
