# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ertaapp', '0012_auto_20180204_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'تمرینی'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'محتوایی'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'درسی'},
        ),
        migrations.AlterModelOptions(
            name='coursemember',
            options={'verbose_name': 'عضوی'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ertaapp.Course', verbose_name=' نام درس '),
        ),
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_author', to=settings.AUTH_USER_MODEL, verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ertaapp.ContentCat', verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='content',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ertaapp.Course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=15, unique=True, verbose_name='کد درس'),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ertaapp.Course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام'),
        ),
    ]
