# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertaapp', '0015_auto_20180205_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, default='course_pics/default_course.png', upload_to='course_pics'),
        ),
    ]
