"""
Django settings for ertasite project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, 'ertaapp/templates/ertaapp')
STATIC_DIR = os.path.join(BASE_DIR, 'static')
MEDIA_DIR = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
TINYMCE_JS_URL = '//cdn.tinymce.com/4/tinymce.min.js'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'reset_migrations',
    'copyright',
    'tinymce',
    'django.contrib.staticfiles',
    'bootstrap3',
    'ertaapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'ertasite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ertasite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS':{'min_length':9}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Iran'

USE_I18N = True

USE_L10N = True

USE_TZ = True

COPY_START_YEAR = 2017

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = STATIC_DIR
STATICFILES_DIR = [STATIC_DIR, ]
MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = '/media/'
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"



# TINYMCE_DEFAULT_CONFIG = {
# 'theme': "modern", # default value
# 'theme_advanced_resizing': True,
# 'relative_urls': True, # default value
# 'content_style': '.mcecontentbody{font-size:19px;}',
# 'plugins': 'table,spellchecker,paste,searchreplace,',
# 'theme_advanced_buttons1': 'bold,hr,,code,autolink,preview,italic,underline,bullist,numlist,link,unlink,separator,undo,redo,fontselect,fontsizeselect',
# 'width': '100%',
# 'height': 300,
# 'paste_text_sticky': True,
# 'paste_text_sticky_default': True,
# 'valid_styles': 'font-weight,font-style,text-decoration',
# 'fontsize_formats': "8pt 10pt 11pt 12pt 13pt 14pt 16pt 18pt 20pt 24pt 36pt",
# 'font_formats': "Andale Mono=andale mono,times;" +
#     "Arial=arial,helvetica,sans-serif;" +
#     "Arial Black=arial black,avant garde;" +
#     "Book Antiqua=book antiqua,palatino;" +
#     "Comic Sans MS=comic sans ms,sans-serif;" +
#     "Courier New=courier new,courier;" +
#     "Georgia=georgia,palatino;" +
#     "Helvetica=helvetica;" +
#     "Impact=impact,chicago;" +
#     "Symbol=symbol;" +
#     "Tahoma=tahoma,arial,helvetica,sans-serif;" +
#     "Terminal=terminal,monaco;" +
#     "Times New Roman=times new roman,times;" +
#     "Trebuchet MS=trebuchet ms,geneva;" +
#     "Verdana=verdana,geneva;" +
#     "Webdings=webdings;" +
#     "Wingdings=wingdings,zapf dingbats",}
# TINYMCE_COMPRESSOR = True
